<a href="https://colab.research.google.com/github/yourshashwat/machine_learning/blob/main/day26-ordinal-encoding/day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
url="https://raw.githubusercontent.com/yourshashwat/machine_learning/refs/heads/main/day26-ordinal-encoding/customer.csv"


In [5]:
df = pd.read_csv(url)

In [6]:
df.sample(5)

,age,gender,review,education,purchased
37,94,Male,Average,PG,Yes
29,83,Female,Average,UG,Yes
47,38,Female,Good,PG,Yes
17,22,Female,Poor,UG,Yes
21,32,Male,Average,PG,No


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], train_size=0.8)

In [ ]:
#X_train

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
X_train

,review,education
5,Average,School
47,Good,PG
26,Poor,PG
8,Average,UG
32,Average,UG
21,Average,PG
1,Poor,UG
11,Good,UG
12,Poor,School
7,Poor,School


In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train

,review,education
5,Average,School
47,Good,PG
26,Poor,PG
8,Average,UG
32,Average,UG
21,Average,PG
1,Poor,UG
11,Good,UG
12,Poor,School
7,Poor,School


In [ ]:
X_train = oe.transform(X_train)
X_test= oe.transform(X_test)

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

array([[1., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [0., 1.],
       [0., 1.]])

In [ ]:
X_test

array([[1., 1.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [0., 2.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(Y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [ ]:
Y_train

array([1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1])

In [ ]:
Y_test

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 1])

In [ ]:
X_train_original= oe.inverse_transform(X_train)
X_train_original= pd.DataFrame(X_train_original, columns=['review','education'])
X_train_original


,review,education
0,Average,School
1,Good,PG
2,Poor,PG
3,Average,UG
4,Average,UG
5,Average,PG
6,Poor,UG
7,Good,UG
8,Poor,School
9,Poor,School


In [1]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful